# Nixpacks configuration for Railway deployment
[variables]
NIXPACKS_PHP_VERSION = "php82"

[phases.setup]
nixPkgs = ["php82", "nginx", "bash", "composer"]

[phases.install]
cmds = [
  "composer --version",
  "composer install --no-dev --optimize-autoloader --verbose",
  "ls -la vendor/"
]

[start]
cmd = "php launcher.php"