# Nixpacks configuration for Railway deployment
[variables]
NIXPACKS_PHP_VERSION = "php82"

[phases.setup]
nixPkgs = ["php82", "nginx", "bash"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[start]
cmd = "php launcher.php"