version = "2"

[build]
builder = "nixpacks"

[deploy]
startCommand = "php -S 0.0.0.0:$PORT -t ."

[env]
# Railway will automatically provide these
PORT = { default = "8080" }
RAILWAY_ENVIRONMENT = { default = "production" }

[healthcheck]
path = "/"