version = "2"

[build]
builder = "nixpacks"

[deploy]
startCommand = "php launcher.php"

[env]
# Railway will automatically provide these
PORT = { default = "8080" }
RAILWAY_ENVIRONMENT = { default = "production" }

[healthcheck]
path = "/"